# Project Information
site_name: 灵境记录
site_description: 灵境记录
site_author: w
site_url: https://github.com/Winnie-Lian/lingjing.github.io

# Repository
repo_name: 'Winnie-Lian/lingjing.github.io'
repo_url: 'https://github.com/Winnie-Lian/lingjing.github.io'
edit_uri: 'blob/master/docs/'

use_directory_urls: false

nav:
 - '首页': 'index.md'
 - 'recording': 
   - 'April': 'recording.md'

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins:
    - search

markdown_extensions:
  - admonition
  - codehilite
